# using docker-compose version 1
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes: ['./:/app']
  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E 
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
    depends_on:
      - redis
    volumes: ['./:/queue']
  monitor:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: ['celery', '-A', 'tasks', 'worker']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker 
    volumes: ['./:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
